### ISSUE TITLE
 Error: The object parameter must be exactly 40 characters and contain only [0-9a-f].

### ISSUE THREAD

**Issue by fredbradley** [miguelfito/github-bump-and-tag-action#3]
When I run this, I consistently get this error: 

`Error: The object parameter must be exactly 40 characters and contain only [0-9a-f].`

But I've no idea what it's referring to?

**Comment by miguelfito** [comment]
Hi @fredbradley,

Would you be so kind giving more information about the context of this error? How are you using / invoking this action? Do you have extended log?

I suppose this error message could be related to git SHA commit given to be tagged (fccbb053de9a128f3229b5fcebad4015f1a7b669 >> `fccbb053de9a128f3229b5fcebad4015f1a7b669`) or with [`github_token` param](https://docs.github.com/es/github/authenticating-to-github/creating-a-personal-access-token) due `[0-9a-f]` limitation.

**Comment by fredbradley** [comment]
thanks for being speedy... 

I'm guessing I need a little more explanation about how the script works, what it expects, etc... 

Here's the error output: 

![image](https://user-images.githubusercontent.com/1639226/109016762-64a73980-76ae-11eb-9058-c032c3e6e7ec.png)

I'm currently testing different actions in order to create a suitable sequence for my production app.

**Comment by fredbradley** [comment]
I wasn't passing `commit_sha` at all - All I did was copy the code on your readme. 

```
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: miguelfito/github-bump-and-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
```

**Comment by miguelfito** [comment]
Take a look on this example, where I first run this action in `dry_run` mode to get next tag version (`id: tag_version`), then update & commit this new version on `package.json` and finally run again this action over this last bumping version commit to generate and tag the GitHub Release: 


```yaml
# A GitHub Action to automatically bump and tag master, with the latest SemVer formatted version.
name: Generate new release & version

on:
    - workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main branch to calculate changelog
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Calculate version
              id: tag_version
              uses: miguelfito/github-bump-and-tag-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  default_bump: patch
                  create_annotated_tag: true
                  tag_prefix: v
                  dry_run: true

            - name: Set npm package version
              uses: reedyuk/npm-version@1.0.1
              with:
                version: ${{ steps.tag_version.outputs.new_version }}

            - name: Commit & push version bumping on package*.json
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: master
                  file_pattern: package*.json
                  commit_message: 'chore(release): Automated version bumping to ${{ steps.tag_version.outputs.new_tag }}'
                  commit_user_name: GitHub Actions
                  commit_user_email: actions@github.com

            - name: Get updated commit SHA
              run: |
                echo "##[set-output name=commit_id;]$(git rev-parse HEAD)"
              id: updated_sha

            - name: Bump version and push tag
              uses: miguelfito/github-bump-and-tag-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  commit_sha: ${{ steps.updated_sha.outputs.commit_id }}
                  default_bump: patch
                  create_annotated_tag: true
                  tag_prefix: v

            - name: Create a GitHub release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_SHA: ${{ steps.updated_sha.outputs.commit_id }}
              with:
                  commitish: ${{ steps.updated_sha.outputs.commit_id }}
                  tag_name: ${{ steps.tag_version.outputs.new_tag }}
                  release_name: Release ${{ steps.tag_version.outputs.new_tag }}
                  body: ${{ steps.tag_version.outputs.changelog }}
```
